### ISSUE TITLE
OSS Review

### ISSUE THREAD

**Issue by tyvsmith** [uber/nanoscope#49]
- Needs top title for repo
- Needs contributing guidelines in Readme
- Add license to Readme and add license file to repo
- Needs Travis file for builds and verification.
- This is referencing the rom version on AWS, where is the code for the rom and the viewer? Separate Repo, if so, what's the plan to communicate those?

The Readme feels really light right now, definitely flesh out with a better description and some value propositions this has.

cc @briankhsieh

**Comment by Leland-Takamine** [comment]
Spoke offline - updated READMEs. Will work on figuring out a plan for CI.
