### ISSUE TITLE
Control trace start and end

### ISSUE THREAD

**Issue by dodola** [uber/nanoscope#57]
request a feature to get a small range trace ，like begin  `MainActivity.onCreate` to `MainActivity.onResume` all method traces.

**Comment by Leland-Takamine** [comment]
This is possible today, though the workflow is a bit clunky:

1. Use the [Java API](https://github.com/uber/nanoscope/wiki/Architecture%3A-Nanoscope-ROM#java-api) to set start and stop tracing points.
2. `adb pull` the file off the device.
3. Open the file in the Nanoscope Visualizer with `nanoscope open <trace-file>`.

Let me know if you have any suggestions to improve this workflow.

**Comment by dodola** [comment]
Oh Thank you. It is very useful
