### ISSUE TITLE
Getting Error "emulator: Trying to vcpu execute at eip:8f131b"

### ISSUE THREAD

**Issue by vishalgupta1987** [uber/nanoscope#68]
When using command "nanoscope emulator"

Error Message shows "emulator: Trying to vcpu execute at eip:8f131b" on command line and emulator closed silently

**Comment by Leland-Takamine** [comment]
Hm looks like this is similar to the issue [here](https://github.com/intel/haxm/issues/97)? I'd like to update to Qemu 2 as suggested in that issue, but I'm running into some issues. I'll update this thread if I figure it out.

**Comment by esafirm** [comment]
@Leland-Takamine have you figure it out? Also, how do i know if i use qemu1 or qemu2?

**Comment by tmelz** [comment]
Downgrading to v7.2.0 is a workaround

Uninstall:
```
sudo /Library/Extensions/intelhaxm.kext/Contents/Resources/uninstall.sh
```
Download and install v7.2.0: https://github.com/intel/haxm/releases/tag/v7.2.0

**Comment by BestQiang** [comment]
> 降级到v7.2.0是一种解决方法
> 
> 卸载：
> 
> ```
> sudo /Library/Extensions/intelhaxm.kext/Contents/Resources/uninstall.sh
> ```
> 下载并安装v7.2.0：[https](https://github.com/intel/haxm/releases/tag/v7.2.0)：[//github.com/intel/haxm/releases/tag/v7.2.0](https://github.com/intel/haxm/releases/tag/v7.2.0)

亲测可行

**Comment by Leland-Takamine** [comment]
The latest version of Nanoscope creates a proper AVD with the nanoscope emulator command. Please update to the latest version brew upgrade nanoscope and re-open if this doesn't fix your issue.
