### ISSUE TITLE
Nexus 6P with nanoscope's pre-built ROM cannot boot after reboot.

### ISSUE THREAD

**Issue by jackluo923** [uber/nanoscope#71]
Android ROM (v0.2.3) boots normally directly after fastboot ROM flash. However, subsequent boot will get stuck on screen with white "Google" text with small lock icon on the bottom of the screen.
Is this a known problem with the newest release or do I have a special Nexus 6P?

**Comment by awelc** [comment]
I have just retried with instructions from the README and everything works for me - I tested both flashing and generation of extended trace. Perhaps you can try rebooting to recovery (assuming you have custom recovery flashed, for example TWRP) and do advanced wipe (everything but "Internal Storage"). Please also bear in mind that some Nexus 6P-s can go into infinite bootloop for no good reason (happened to one of my devices, sadly...), but I can't really provide any help for that...

**Comment by jackluo923** [comment]
Thanks for the confirmation. After your explaination, it seems I might have a semi-faulty Nexus 6P. I have flashed the device using the fastboot command directly with both the pre-build image from nanoscope-art repository as well as self-compiled one using android-7.1.2_r28 AOSP branch with or without the modified ART runtime. In all cases, the device fails to reboot successfully.
