### ISSUE TITLE
"nanoscope emulator" command fails with "no such file or directory"

### ISSUE THREAD

**Issue by andrewmunn** [uber/nanoscope#74]
I just installed nanoscope for the first time and get this when I try to run it. my `$ANDROID_HOME` is set.
```
$ nanoscope emulator
Zip already downloaded: /Users/munn/.nanoscope/roms/MZqhtX7x1poNum1SotQmpw==...
Launching emulator...
./emulator.sh: line 12: /Users/munn/Library/Android/sdk/emulator/emulator64-x86: No such file or directory
```

Any ideas how to fix it?

**Comment by andrewmunn** [comment]
Unfortunately, updating `emulator.sh` to point to `$ANDROID_HOME/emulator/qemu/darwin-x86_64/qemu-system-x86_64` results in:

```
Launching emulator...
emulator: autoconfig: -vendor ./vendor.img
emulator: autoconfig: -datadir .
emulator: Cannot find boot properties file: ./boot.prop

emulator: Found target API sdkVersion: 25

emulator: Invalid int property: 'ro.build.version.incremental:eng.leland.20180507.124526'
emulator: Target arch = 'x86'
emulator: Auto-config: -qemu -cpu qemu32
emulator: ERROR: New emulator backend requires minimum kernel version 3.10+ (currently got lower)
Please make sure you've got updated system images and do not force the specific kernel image together with the engine version
```

I think we need to build a new version of the emulator with a more recent Kernel.

**Comment by aleien** [comment]
Hey!
I really hope that you fixed your issue, but I'll post mine suggestion anyway (:

Had the same issue, fixed it by updating in file ~/.nanoscope/rom/<...>/emulator.sh
`KERNEL_FILE=$ANDROID_HOME/system-images/android-25/google_apis/x86/kernel-qemu` to 
`KERNEL_FILE=$ANDROID_HOME/system-images/android-27/google_apis/x86/kernel-ranchu-64`

and

`$ANDROID_HOME/tools/bin/sdkmanager "system-images;android-25;google_apis;x86"` to
`$ANDROID_HOME/tools/bin/sdkmanager "system-images;android-27;google_apis;x86"`

and your suggestion too (`$ANDROID_HOME/emulator/qemu/darwin-x86_64/qemu-system-x86_64`)

It may be different for your installed emulator versions, I guess. Hope it helps!

**Comment by Leland-Takamine** [comment]
The latest version of Nanoscope creates a proper AVD with the nanoscope emulator command. Please update to the latest version brew upgrade nanoscope and re-open if this doesn't fix your issue.
