### ISSUE TITLE
nanoscope emulator can't run

### ISSUE THREAD

**Issue by YYXWJ** [uber/nanoscope#76]
i try like this,but still can't run emulator
![image](https://user-images.githubusercontent.com/19309378/60490074-6dc4e500-9cd8-11e9-992e-7f616ef61ef9.png)
![image](https://user-images.githubusercontent.com/19309378/60490149-8b924a00-9cd8-11e9-9eb7-2c3ca89376bb.png)

**Comment by Leland-Takamine** [comment]
The latest version of Nanoscope creates a proper AVD with the nanoscope emulator command. Please update to the latest version brew upgrade nanoscope and re-open if this doesn't fix your issue.
