### ISSUE TITLE
emulator: No acpi ini file provided, using default

### ISSUE THREAD

**Issue by YYXWJ** [uber/nanoscope#77]
![image](https://user-images.githubusercontent.com/19309378/60580445-b69f9b00-9db7-11e9-9277-3847c0cc3ac9.png)
![image](https://user-images.githubusercontent.com/19309378/60580457-bacbb880-9db7-11e9-86e1-484c8f7d86b0.png)

**Comment by YYXWJ** [comment]
could you please solve my problem.

**Comment by Leland-Takamine** [comment]
The latest version of Nanoscope creates a proper AVD with the `nanoscope emulator` command. Please update to the latest version `brew upgrade nanoscope` and re-open if this doesn't fix your issue. You will still see the acpi warning but you can safely ignore it.

**Comment by muhammadrizwan0043** [comment]
> could you please solve my problem.

have you fixed this issue ?
