### ISSUE TITLE
can not show the tip at the bottom left

### ISSUE THREAD

**Issue by norven63** [uber/nanoscope#80]
Recent half a month,my nanoscope can not show the tip at the bottom left.
Does anyone have a similar situation？

![image](https://user-images.githubusercontent.com/4413098/65627696-7a6c8700-e002-11e9-985c-f1bf77529107.png)

**Comment by k-kagurazaka** [comment]
I have the same problem after updating nanoscope.

**Comment by adisonhyh** [comment]
I have the same problem

**Comment by adisonhyh** [comment]
I fix this issue by downgrade Chrome to 75.0.3770.80.
nanoscope is not compatible with the latest version of Chrome.

**Comment by Leland-Takamine** [comment]
This should be fixed now in the latest version of Nanoscope.
