### ISSUE TITLE
Install failed.

### ISSUE THREAD

**Issue by TangHuaiZhe** [uber/nanoscope#83]
➜  ~ brew install nanoscope  
==> Installing nanoscope from uber/nanoscope
==> Downloading https://github.com/uber/nanoscope/releases/download/0.2.18/nanos
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
🍺  /usr/local/Cellar/nanoscope/0.2.18: 13 files, 3.7MB, built in 12 seconds
➜  ~ nanoscope emulator                   
Zip already downloaded: /Users/i530643/.nanoscope/roms/L2Xyj8R6fKIhj37bsgVYYg==...
Launching emulator...
emulator:Android emulator version 26.0.3.0 (build_id 3965150)
emulator:Found AVD name 'nanoscope'
PANIC: Unknown AVD name [nanoscope], use -list-avds to see valid list.
HOME is defined but there is no file nanoscope.ini in $HOME/.android/avd
(Note: Directories are searched in the order $ANDROID_AVD_HOME, $ANDROID_SDK_HOME/avd, and $HOME/.android/avd)

**Comment by pyricau** [comment]
Same here, I fixed it with `rm -rf $ANDROID_HOME/system-images/nanoscope`

**Comment by TangHuaiZhe** [comment]
@pyricau Thanks! 
The solution works for me.
